version: "3.9"

services:
  spark-master:
    image: bitnami/spark:3.5.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"   # spark://... для воркеров/клиента
      - "8080:8080"   # web UI мастера
    volumes:
      - ./:/app
    networks:
      - spark-net

  spark-worker:
    image: bitnami/spark:3.5.1
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
    volumes:
      - ./:/app
    networks:
      - spark-net

  # “клиент”, из которого удобно делать spark-submit
  spark-submit:
    image: bitnami/spark:3.5.1
    container_name: spark-submit
    working_dir: /app
    depends_on:
      - spark-master
      - spark-worker
    volumes:
      - ./:/app
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
